---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: authkeysync-default
    image: ubuntu:24.04
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
