---
- name: Converge with proxy
  hosts: all
  become: false
  gather_facts: true
  roles:
    - role: mikroways.authkeysync
      vars:
        authkeysync_http_proxy: "http://127.0.0.1:8888"
        authkeysync_https_proxy: "http://127.0.0.1:8888"
